event2zeitpunkt_table <- data.table(
  EVENTref = c(1L, 0L, 2L, 31L, 321L, 3L, 4L, 5L,
               6L, 7L, 13L, 14L, 28L, 8L, 9L, 10L, 11L, 12L, 15L),
  zeitpunktref = c(-2, -1, -0.75, -0.5, -0.25, 0, 1, 2, 3, 4, 5, 6, 27, 28,
                   180, 360, 500, 1000, NA),
  zp_fabianref = c("auf", "auf+d0", "d-1", "auf_in_d0",
                   "auf_in_d-1_in_d0", "d0", "d1", "d2", "d3", "d4", "d4.2",
                   "d4.3", "d5", "d5.1", "d6", "d7", "d8", NA, NA),
  zp_fabian1DayBefore = c(NA, NA, NA, NA, NA, NA, "d0", "d1", "d2", "d3",
                          "d4", "d4.2", NA, NA, NA, NA, NA, NA, NA),
  EVENTKombination = c(FALSE, TRUE, FALSE, TRUE, TRUE, FALSE, FALSE, FALSE,
                       FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE,
                       FALSE, FALSE, FALSE),
  Erklaerung =
    c("Aufnahme, kann 0-48h vor Einschluss liegen",
      "Schlimmster Wert bzgl. Einschluss und Aufnahme",
      "Pre-Einschluss, kann 0-24h vor Einschluss liegen, kann selten vor Aufnahme liegen",
      "Einschluss, falls NA Aufnahme",
      "Einschluss, falls NA Pre-Einschluss, falls NA Aufnahme",
      "Einschluss",
      "Visite1, 12-36 h nach Einschluss",
      "Visite2, 24h nach Visite1",
      "Visite3, 24h nach Visite2",
      "Visite4, 24h nach Visite3",
      "Visite5, 24h nach Visite5",
      "Visite6, 24h nach Visite5",
      "Zeitraum letzte Visite (4 od.6) bis 28 Tage nach Einschluss ",
      "Situation 28 Tage nach Einschluss",
      "Situation 180 Tage nach Einschluss",
      "Situation 360 Tage nach Einschluss",
      "Situation bei Studienende",
      "unvorhergesehenes EVENT,kann irgendwas irgendwann sein",
      "zeitlich invariantes Ereignis von CAPSyS"
    )
)
